import Head from "next/head";
import HomeProfile from "~/components/home/home-profile";
import Posts from "~/components/shared/post/posts";

export default function Home() {
  return (
    <>
      <Head>
        <title>Threads</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex min-h-screen max-w-4xl gap-16 px-4 md:ml-20 lg:ml-[34%] lg:p-0 lg:pt-8">
        <Posts />
        <HomeProfile />
      </main>
    </>
  );
}
