import { Notification, User } from "@prisma/client";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { api } from "~/utils/api";
import { formatToNowDate } from "~/utils/formatToNowDate";

interface NotificationWithUser extends Notification {
  user: User;
}

export default function Home() {
  const { data: session } = useSession();

  const { data: notifications } =
    api.notifications.getNotificationsByUser.useQuery(
      {
        userId: session?.user.id as string,
      },
      {
        refetchOnWindowFocus: false,
      }
    );

  const formatNotificationType = (type: string) => {
    switch (type) {
      case "follow":
        return "followed you";
      case "like":
        return "liked your post";
      case "reply":
        return "replied to your post";
      case "mention":
        return "mentioned you in a post";
      default:
        return "did something";
    }
  };

  return (
    <>
      <Head>
        <title>Threads | Notifications</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto min-h-screen max-w-2xl gap-16 px-4 md:ml-20 lg:ml-[34%] lg:p-0">
        <h1 className="text-3xl font-bold">Activity</h1>

        {session?.user ? (
          <div className="mt-3">
            <ul>
              {notifications && notifications.length > 0 ? (
                notifications.map((notification: NotificationWithUser) => (
                  <li className="flex w-full gap-3 pt-2" key={notification.id}>
                    <div className="h-11 w-11 flex-shrink-0 overflow-hidden rounded-full">
                      <Image
                        src={notification.user.image as string}
                        alt={notification.user.name as string}
                        fill
                        className="!relative h-full w-full object-cover"
                      />
                    </div>
                    <div className="w-full border-b border-accent pb-3">
                      <div className="flex items-center gap-2">
                        <h4 className="text-base font-semibold">
                          {notification.user.name}
                        </h4>
                        <span className="text-sm text-foreground">
                          {formatToNowDate(new Date(notification.createdAt))}
                        </span>
                      </div>
                      <p className="m-0 text-base text-foreground">
                        {formatNotificationType(notification.type)}
                      </p>
                    </div>
                  </li>
                ))
              ) : (
                <span className="text-lg text-foreground">
                  No new notifications
                </span>
              )}
            </ul>
          </div>
        ) : (
          <span className="text-lg text-foreground">
            You need to login to see notifications
          </span>
        )}
      </main>
    </>
  );
}
