import { useSession } from "next-auth/react";
import Head from "next/head";
import { useState } from "react";
import PostUser from "~/components/shared/post/post-user";
import { api } from "~/utils/api";
import toast from "react-hot-toast";
import Button from "~/components/shared/button";
import TextareaAutosize from "react-textarea-autosize";

export default function ThreadsNew() {
  const { data: session } = useSession();

  const [content, setContent] = useState<string>("");

  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);

  const trpcUtils = api.useContext();

  const createPost = api.posts.create.useMutation({
    onSuccess: (post) => {
      setContent("");
      toast.success("Post created");
      setIsSubmitting(false);
    },
    onError: (error) => {
      toast.error(error.message);
      setIsSubmitting(false);
    },
  });

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (!content)
      return toast.error("Post cannot be empty", {
        id: "post-empty",
      });

    setIsSubmitting(true);
    createPost.mutate({ content });
  };

  if (!session?.user) return null;

  return (
    <>
      <Head>
        <title>Threads</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto min-h-screen max-w-2xl px-4 md:ml-20 lg:ml-[38%] lg:p-0">
        <form onSubmit={handleSubmit}>
          <div className="w-full">
            {session?.user && (
              <PostUser
                id={session?.user.id}
                avatar={session.user.image as string}
                username={session.user.name as string}
                verified
              />
            )}
            <div className="mt-8">
              <TextareaAutosize
                className="w-full resize-none rounded border border-foreground bg-transparent px-4 py-3 outline-none focus:ring-2 focus:ring-foreground"
                placeholder="Start a thread..."
                value={content}
                disabled={isSubmitting}
                onChange={(event) => setContent(event.target.value)}
              />

              <span className="text-sm font-semibold text-foreground">
                {content.length}/500
              </span>
            </div>

            <div className="flex justify-end">
              <Button disabled={isSubmitting} type="submit">
                Post
              </Button>
            </div>
          </div>
        </form>
      </main>
    </>
  );
}
