import { useSession } from "next-auth/react";
import Head from "next/head";
import { useState } from "react";
import PostUser from "~/components/shared/post/post-user";
import { api } from "~/utils/api";
import toast from "react-hot-toast";

export default function ThreadsNew() {
  const { data: session } = useSession();

  const [content, setContent] = useState<string>("");

  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);

  const trpcUtils = api.useContext();

  const createPost = api.posts.create.useMutation({
    onSuccess: (post) => {
      setContent("");
      toast.success("Post created");
      setIsSubmitting(false);

      // const updateData = (posts: any) => {
      //   return [post, ...posts];
      // };

      // trpcUtils.posts.getAll.setData(undefined, updateData);

      // trpcUtils.invalidateQuery(["posts.getAll"]);
    },
  });

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (!content) return alert("Please enter some content");

    setIsSubmitting(true);
    createPost.mutate({ content });
  };

  if (!session?.user) return null;

  return (
    <>
      <Head>
        <title>Threads</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto min-h-screen max-w-2xl px-4 md:ml-20 lg:ml-[38%] lg:p-0">
        <form onSubmit={handleSubmit}>
          <div className="w-full">
            {session?.user && (
              <PostUser
                id={session?.user.id}
                avatar={session.user.image as string}
                username={session.user.name as string}
                verified
              />
            )}
            <div className="mt-8">
              <textarea
                className="w-full rounded border bg-transparent px-4 py-3"
                placeholder="Start a thread..."
                value={content}
                disabled={isSubmitting}
                onChange={(event) => setContent(event.target.value)}
              ></textarea>
            </div>

            <div>
              <button disabled={isSubmitting} className="text-xl text-blue-400">
                Post
              </button>
            </div>
          </div>
        </form>
      </main>
    </>
  );
}
